version: '3.8'
services:
  vprodb:
    build: 
     context: ./Docker-files/db
    image: beginner22/vprofileapp-db-mysql
    container_name: vprodb 
    ports:
    - "3306:3306" 
    volumes:
    - vprodbdata:/var/lib/mysql 
    environment:
    - MYSQL_ROOT_PASSWORD=vorodbpass 

  vproapp:
    build: 
     context: ./Docker-files/app
    image: beginner22/vprofileapp-app-tomcat
    container_name: vproapp 
    ports:
    - "8080:8080" 
    volumes:
    - vproappdata:/usr/local/tomcat/webapps 
  
  vproweb:
    build: 
     context: ./Docker-files/web
    image: beginner22/vprofileapp-web-nginx
    container_name: vproweb 
    ports:
    - "80:80"  
  
  vprocache01:
    image: memcached 
    port: 
    - "11211:11211"

  vpromq01:
    image: rabbitmq
    port:
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_PASS=guest
      RABBITMQ_DEFAULT_USER=guest
    

volumes:
  vprodbdata: {}
  vproappdata: {}

